In [2]:
import numpy as np
import math
import matplotlib.pyplot as plt
from Scripts.beams import BeamType
from Scripts.beams import BeamSystem
print("?")
beam_system = BeamSystem("system")
arm_beam = BeamType("annulus", [0.025, 0.018], "Aluminum7075-T6", "arm_beam")
beam_system.add_node(0,0,0,"origin")
beam_system.add_node(1,0,0,"point_1")
beam_system.add_beam(arm_beam,"origin","point_1",np.array([0,1,0]),"beam")
beam_system.add_boundary_condition(0,"x","origin")
beam_system.add_boundary_condition(0,"y","origin")
beam_system.add_boundary_condition(0,"z","origin")
beam_system.add_boundary_condition(0,"theta x","origin")
beam_system.add_boundary_condition(0,"theta y","origin")
beam_system.add_boundary_condition(0,"theta z","origin")
beam_system.add_boundary_condition(0,"x","point_1")
beam_system.add_boundary_condition(0,"y","point_1")
beam_system.add_boundary_condition(0,"theta x","point_1")
beam_system.add_boundary_condition(0,"theta z","point_1")
beam_system.add_force(0,0,-1,"point_1")
beam_system.solve_FEA()
I = (math.pi/64) * (0.025**4 - 0.018**4)
E = 6.89e7
#print("z:",1/(3*I*E))
#print("d: ",beam_system.displacement_angle_vector)
#print("r: ",beam_system.force_moment_vector)
print("k: ",beam_system.beams[0].transformation_matrix)

?
[1. 0. 0.]
t:  [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[ 6.51531759e+04  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00 -6.51531759e+04
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  3.67812169e+02  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.83906084e+02  1.83906084e+02  0.00000000e+00
  -3.67812169e+02  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.84695188e+02  0.00000000e+00
  -9.23475938e+01  0.00000000e+00  0.00000000e+00 

LinAlgError: Singular matrix