In [8]:
import numpy as np
import math
import matplotlib.pyplot as plt
from Scripts.beams import BeamType
from Scripts.beams import BeamSystem

In [2]:
beam_system = BeamSystem("Cantilever-end load")
arm_beam = BeamType("annulus", [25, 20], "Aluminum7075-T6", "arm_beam")
beam_system.add_node(0,0,0,"origin")
beam_system.add_node(500,0,0,"point_1")
beam_system.add_beam(arm_beam,"origin","point_1",np.array([0,1,0]),"beam")
beam_system.add_boundary_condition(0,"x","origin")
beam_system.add_boundary_condition(0,"y","origin")
beam_system.add_boundary_condition(0,"z","origin")
beam_system.add_boundary_condition(0,"theta x","origin")
beam_system.add_boundary_condition(0,"theta y","origin")
beam_system.add_boundary_condition(0,"theta z","origin")
beam_system.add_force(0,0,-4,"point_1")
# beam_system.add_moment(0,400,0,"point_1")
beam_system.solve_FEA()
L = 500
I = (math.pi/64) * (50**4 - 40**4)
E = 71.7
F = 4
# kuu 
# Z1  Z2
# Z2  Z3
y = - (F * L ** 3) / (3*E*I)
m = F * L
dydx = (F*L**2)/(2*E*I) - (F*L**2)/(E*I)

print(beam_system.beams[0].transformation_matrix)
print(beam_system.kuu @ beam_system.du)

# print(beam_system.kuu)
print("Cantilever—end load")
print("calculated z: " + str(y) + " | FEA z: " + str(beam_system.z_displacements[1]))
print("calculated theta: " + str(dydx) + " | FEA reaction theta: " + str(beam_system.y_angles[1]))
print("calculated moment: " + str(m) + " | FEA moment: " + str(beam_system.y_moments[0]))
print("calculated reaction: " + str(F) + " | FEA reaction z: " + str(beam_system.z_forces[0]))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[ 0.  0. -4.  0.  0.  0.]
Cantilever—end load
calculated z: -12.833151729870774 | FEA z: -12.890782971234628
calculated theta: -0.03849945518961233 | FEA reaction theta: 0.03849945518961232
calculated moment: 2000 | FEA moment: -1999.9999999999998
calculated reaction: 4 | FEA reaction z: 3.9999999999999982


In [3]:
beam_system = BeamSystem("Simple Support Center Load")
arm_beam = BeamType("annulus", [25, 20], "Aluminum7075-T6", "arm_beam")
beam_system.add_node(0,0,0,"origin")
beam_system.add_node(500,0,0,"point_1")
beam_system.add_node(1000,0,0,"point_2")
beam_system.add_beam(arm_beam,"origin","point_1",np.array([0,1,0]),"beam")
beam_system.add_beam(arm_beam,"point_1","point_2",np.array([0,1,0]),"beam")
beam_system.add_boundary_condition(0,"x","origin")
beam_system.add_boundary_condition(0,"y","origin")
beam_system.add_boundary_condition(0,"z","origin")
beam_system.add_boundary_condition(0,"theta x","origin")
beam_system.add_boundary_condition(0,"theta y","origin")
beam_system.add_boundary_condition(0,"x","point_1")
beam_system.add_boundary_condition(0,"z","point_1")
beam_system.add_boundary_condition(0,"x","point_2")
beam_system.add_boundary_condition(0,"y","point_2")
beam_system.add_boundary_condition(0,"z","point_2")
beam_system.add_boundary_condition(0,"theta x","point_2")
beam_system.add_boundary_condition(0,"theta y","point_2")
beam_system.add_force(0,-4,0,"point_1")
beam_system.solve_FEA()

L = 1000
I = (math.pi/64) * (50**4 - 40**4)
E = 71.7
F = 4

y = -(F * (L**3)) / (48 * E * I)
r = F/2
dydx = -(F * L ** 2) / (16 * E * I)

print("Simple Support Center Load")
print("calculated y: " + str(y) + " | FEA y: " + str(beam_system.y_displacements[1]))
print("calculated moment: " + str(0) + " | FEA moment: " + str(beam_system.z_moments[1]))
print("calculated theta center: " + str(0) + " | FEA theta center: " + str(beam_system.z_angles[1]))
print("calculated theta origin: " + str(dydx) + " | FEA theta origin: " + str(beam_system.z_angles[0]))
print("calculated theta edge: " + str(-dydx) + " | FEA theta edge: " + str(beam_system.z_angles[2]))
print("calculated reaction y: " + str(r) + " | FEA reaction y: " + str(beam_system.y_forces[0]))

Simple Support Center Load
calculated y: -6.416575864935387 | FEA y: -6.4453914856173125
calculated moment: 0 | FEA moment: 0.0
calculated theta center: 0 | FEA theta center: 3.029190364209772e-19
calculated theta origin: -0.019249727594806164 | FEA theta origin: -0.019249727594806157
calculated theta edge: 0.019249727594806164 | FEA theta edge: 0.019249727594806157
calculated reaction y: 2.0 | FEA reaction y: 1.9999999999999991


In [4]:
beam_system = BeamSystem("Cantilever-moment load")
arm_beam = BeamType("annulus", [25, 20], "Aluminum7075-T6", "arm_beam")
beam_system.add_node(0,0,0,"origin")
beam_system.add_node(500,0,0,"point_1")
beam_system.add_beam(arm_beam,"origin","point_1",np.array([0,1,0]),"beam")
beam_system.add_boundary_condition(0,"x","origin")
beam_system.add_boundary_condition(0,"y","origin")
beam_system.add_boundary_condition(0,"z","origin")
beam_system.add_boundary_condition(0,"theta x","origin")
beam_system.add_boundary_condition(0,"theta y","origin")
beam_system.add_boundary_condition(0,"theta z","origin")
beam_system.add_boundary_condition(0,"theta x","point_1")
beam_system.add_boundary_condition(0,"theta z","point_1")
beam_system.add_moment(0,4,0,"point_1")
beam_system.solve_FEA()

L = 500
I = (math.pi/64) * (50**4 - 40**4)
E = 71.7
M = 4

y = (M * L ** 2) / (2 * E * I)
dydx = M * L / (E * I)

# print(beam_system.kuu)
print("Cantilever—moment load")
print("calculated z: " + str(y) + " | FEA z: " + str(beam_system.z_displacements[1]))
print("calculated theta: " + str(dydx) + " | FEA theta: " + str(beam_system.y_angles[1]))
print("calculated reaction force z: " + str(0) + " | FEA reaction z: " + str(beam_system.z_forces[0]))
print("calculated reaction moment y: " + str(-M) + " | FEA reaction moment y: " + str(beam_system.y_moments[0]))

Cantilever—moment load
calculated z: 0.03849945518961233 | FEA z: -0.038499455189612314
calculated theta: 0.0001539978207584493 | FEA theta: 0.00015399782075844928
calculated reaction force z: 0 | FEA reaction z: -6.938893903907228e-18
calculated reaction moment y: -4 | FEA reaction moment y: -3.9999999999999964


In [5]:
beam_system = BeamSystem("Cantilever-end load rectangle")
arm_beam = BeamType("rectangle", [25, 10], "Aluminum7075-T6", "arm_beam")
beam_system.add_node(0,0,0,"origin")
beam_system.add_node(500,0,0,"point_1")
beam_system.add_beam(arm_beam,"origin","point_1",np.array([0,0,1]),"beam")
beam_system.add_boundary_condition(0,"x","origin")
beam_system.add_boundary_condition(0,"y","origin")
beam_system.add_boundary_condition(0,"z","origin")
beam_system.add_boundary_condition(0,"theta x","origin")
beam_system.add_boundary_condition(0,"theta y","origin")
beam_system.add_boundary_condition(0,"theta z","origin")
beam_system.add_boundary_condition(0,"x","point_1")
beam_system.add_boundary_condition(0,"y","point_1")
beam_system.add_boundary_condition(0,"theta x","point_1")
beam_system.add_boundary_condition(0,"theta z","point_1")
beam_system.add_force(0,0,-4,"point_1")
beam_system.solve_FEA()

L = 500
I = (math.pi/64) * (50**4 - 40**4)
E = 71.7
F = 4
# kuu 
# Z1  Z2
# Z2  Z3
y = - (F * L ** 3) / (3*E*I)
m = F * L
dydx = (F*L**2)/(2*E*I) - (F*L**2)/(E*I)

# print(beam_system.kuu)
print("Cantilever—end load rectangle")
print("calculated z: " + str(y) + " | FEA z: " + str(beam_system.z_displacements[1]))
print("calculated moment: " + str(m) + " | FEA moment: " + str(beam_system.y_moments[0]))
print("calculated reaction: " + str(F) + " | FEA reaction z: " + str(beam_system.z_forces[0]))
print("calculated theta: " + str(dydx) + " | FEA reaction theta: " + str(beam_system.y_angles[1]))

Cantilever—end load rectangle
calculated z: -12.833151729870774 | FEA z: -178.76944932675897
calculated moment: 2000 | FEA moment: -1999.9999999999995
calculated reaction: 4 | FEA reaction z: 4.0
calculated theta: -0.03849945518961233 | FEA reaction theta: 0.5355648535564851


In [6]:
beam_system = BeamSystem("Multidimensional Simple Support Center Load")
arm_beam = BeamType("annulus", [25, 20], "Aluminum7075-T6", "arm_beam")
beam_system.add_node(-1000,-1000,-1000,"point_0")
beam_system.add_node(0,0,0,"point_1")
beam_system.add_node(1000,1000,1000,"point_2")
beam_system.add_beam(arm_beam,"point_0","point_1",np.array([0,-1,1]),"beam")
beam_system.add_beam(arm_beam,"point_1","point_2",np.array([0,-1,1]),"beam")
beam_system.add_boundary_condition(0,"x","point_0")
beam_system.add_boundary_condition(0,"y","point_0")
beam_system.add_boundary_condition(0,"z","point_0")
beam_system.add_boundary_condition(0,"x","point_2")
beam_system.add_boundary_condition(0,"y","point_2")
beam_system.add_boundary_condition(0,"z","point_2")
beam_system.add_force(0,-1,1,"point_1")
beam_system.solve_FEA()

L = math.sqrt(3 * 2000 ** 2)
I = (math.pi/64) * (50**4 - 40**4)
E = 71.7
F = math.sqrt(2)
# kuu 
# Z1  Z2
# Z2  Z3
y = -(F * (L**3)) / (48 * E * I)
r = F/2
dydx = -(F * L ** 2) / (16 * E * I)


print("Multidimensional Simple Support Center Load")
print("FEA x: " + str(beam_system.x_displacements[1]))
print("FEA y: " + str(beam_system.y_displacements[1]))
print("FEA z: " + str(beam_system.z_displacements[1]))
print("FEA x theta: " + str(beam_system.x_angles[1]))
print("FEA y theta: " + str(beam_system.y_angles[1]))
print("FEA z theta: " + str(beam_system.z_angles[1]))
print("FEA x reaction: " + str(beam_system.x_forces[0]))
print("FEA y reaction: " + str(beam_system.y_forces[0]))
print("FEA z reaction: " + str(beam_system.z_forces[0]))

total_fea_disp = math.sqrt(beam_system.x_displacements[1] ** 2 + beam_system.y_displacements[1] ** 2 + beam_system.z_displacements[1] ** 2)
total_fea_reaction = math.sqrt(beam_system.x_forces[0] ** 2 + beam_system.y_forces[0] ** 2 + beam_system.z_forces[0] ** 2)

print("Calculated total displacement: " + str(y) + " | Total displacement FEA: " + str(total_fea_disp))
print("Calculated total reaction: " + str(r) + " | Total reaction FEA: " + str(total_fea_reaction))

print("Transformation matrix: " + str(np.round(beam_system.beams[0].transformation_matrix,3)))

Multidimensional Simple Support Center Load
FEA x: 2.8859968597745555e-15
FEA y: -66.70796751165817
FEA z: 66.70796751165817
FEA x theta: 0.013633206602974754
FEA y theta: 0.013633206602974754
FEA z theta: 0.013633206602974754
FEA x reaction: 2.6645352591003757e-15
FEA y reaction: 0.4999999999997136
FEA z reaction: -0.4999999999998007
Calculated total displacement: -94.30402058969597 | Total displacement FEA: 94.33931237333078
Calculated total reaction: 0.7071067811865476 | Total reaction FEA: 0.7071067811862041
Transformation matrix: [[ 0.577  0.577  0.577  0.     0.     0.     0.     0.     0.     0.
   0.     0.   ]
 [ 0.    -0.707  0.707  0.     0.     0.     0.     0.     0.     0.
   0.     0.   ]
 [ 0.816 -0.408 -0.408  0.     0.     0.     0.     0.     0.     0.
   0.     0.   ]
 [ 0.     0.     0.     0.577  0.577  0.577  0.     0.     0.     0.
   0.     0.   ]
 [ 0.     0.     0.     0.    -0.707  0.707  0.     0.     0.     0.
   0.     0.   ]
 [ 0.     0.     0.     0.816

C:\Desktop\UAV_Mission\Scripts\beams.py:227: LinAlgWarning: Ill-conditioned matrix (rcond=1.23786e-17): result may not be accurate.
  du = scipy.linalg.solve(kuu, ru - (kup @ dp))


In [12]:
beam_system = BeamSystem("Cantilever-end load xy")
arm_beam = BeamType("annulus", [25, 20], "Aluminum7075-T6", "arm_beam")
beam_system.add_node(0,0,0,"origin")
beam_system.add_node(0,500,0,"point_1")
beam_system.add_beam(arm_beam,"origin","point_1",np.array([0,0,1]),"beam")
beam_system.add_boundary_condition(0,"x","origin")
beam_system.add_boundary_condition(0,"y","origin")
beam_system.add_boundary_condition(0,"z","origin")
beam_system.add_boundary_condition(0,"theta x","origin")
beam_system.add_boundary_condition(0,"theta y","origin")
beam_system.add_boundary_condition(0,"theta z","origin")
beam_system.add_force(-4,0,0,"point_1")
# beam_system.add_moment(0,400,0,"point_1")
beam_system.solve_FEA()
L = 500
I = (math.pi/64) * (50**4 - 40**4)
E = 71.7
F = 4
# kuu 
# Z1  Z2
# Z2  Z3
y = - (F * L ** 3) / (3*E*I)
m = F * L
dydx = (F*L**2)/(2*E*I) - (F*L**2)/(E*I)

print(beam_system.beams[0].transformation_matrix)
print(beam_system.kuu @ beam_system.du)

# print(beam_system.kuu)
print("Cantilever—end load")
print("calculated x: " + str(y) + " | FEA x: " + str(beam_system.x_displacements[1]))
print("calculated theta z: " + str(dydx) + " | FEA reaction theta z: " + str(beam_system.z_angles[1]))
print("calculated moment: " + str(m) + " | FEA moment: " + str(beam_system.z_moments[0]))
print("calculated reaction: " + str(F) + " | FEA reaction x: " + str(beam_system.x_forces[0]))

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
[-4.  0.  0.  0.  0.  0.]
Cantilever—end load
calculated x: -12.833151729870774 | FEA x: -12.890782971234628
calculated theta z: -0.03849945518961233 | FEA reaction theta z: 0.03849945518961232
calculated moment: 2000 | FEA moment: -1999.9999999999998
calculated reaction: 4 | FEA reaction x: 3.9999999999999982


In [19]:
beam_system = BeamSystem("Cantilever-end load xz")
arm_beam = BeamType("annulus", [25, 20], "Aluminum7075-T6", "arm_beam")
beam_system.add_node(0,0,0,"origin")
beam_system.add_node(0,0,500,"point_1")
beam_system.add_beam(arm_beam,"origin","point_1",np.array([0,1,0]),"beam")
beam_system.add_boundary_condition(0,"x","origin")
beam_system.add_boundary_condition(0,"y","origin")
beam_system.add_boundary_condition(0,"z","origin")
beam_system.add_boundary_condition(0,"theta x","origin")
beam_system.add_boundary_condition(0,"theta y","origin")
beam_system.add_boundary_condition(0,"theta z","origin")
beam_system.add_force(-4,0,0,"point_1")
beam_system.solve_FEA()
L = 500
I = (math.pi/64) * (50**4 - 40**4)
E = 71.7
F = 4
# kuu 
# Z1  Z2
# Z2  Z3
y = - (F * L ** 3) / (3*E*I)
m = F * L
dydx = (F*L**2)/(2*E*I) - (F*L**2)/(E*I)

print(beam_system.beams[0].transformation_matrix)
print(beam_system.kuu @ beam_system.du)

print("Cantilever—end load")
print("calculated x: " + str(y) + " | FEA x: " + str(beam_system.x_displacements[1]))
print("calculated theta z: " + str(dydx) + " | FEA reaction theta z: " + str(beam_system.y_angles[1]))
print("calculated moment: " + str(m) + " | FEA moment: " + str(beam_system.y_moments[0]))
print("calculated reaction: " + str(F) + " | FEA reaction x: " + str(beam_system.x_forces[0]))

[[ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.]]
[-4.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  5.02983582e-15  0.00000000e+00]
[[ 1.22477005e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -3.06192513e+02  0.00000000e+00]
 [ 0.00000000e+00  1.22477005e+00  0.00000000e+00  3.06192513e+02
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.01363487e+02  0.00000000e+00
   0.00000000e+00  0