In [5]:
import numpy as np
import math
import matplotlib.pyplot as plt
from Scripts.beams import BeamType
from Scripts.beams import BeamSystem

In [7]:
beam_system = BeamSystem("Cantilever-end load")
arm_beam = BeamType("annulus", [25, 20], "Aluminum7075-T6", "arm_beam")
beam_system.add_node(0,0,0,"origin")
beam_system.add_node(500,0,0,"point_1")
beam_system.add_beam(arm_beam,"origin","point_1",np.array([0,1,0]),"beam")
beam_system.add_boundary_condition(0,"x","origin")
beam_system.add_boundary_condition(0,"y","origin")
beam_system.add_boundary_condition(0,"z","origin")
beam_system.add_boundary_condition(0,"theta x","origin")
beam_system.add_boundary_condition(0,"theta y","origin")
beam_system.add_boundary_condition(0,"theta z","origin")
beam_system.add_force(0,0,-4,"point_1")
beam_system.add_moment(0,400,0,"point_1")
beam_system.solve_FEA()
L = 500
I = (math.pi/64) * (50**4 - 40**4)
E = 71.7
F = 4
# kuu 
# Z1  Z2
# Z2  Z3
y = - (F * L ** 3) / (3*E*I)
m = F * L
dydx = (F*L**2)/(2*E*I) - (F*L**2)/(E*I)

print(beam_system.beams[0].transformation_matrix)
print(beam_system.kuu @ beam_system.du)

# print(beam_system.kuu)
print("Cantilever—end load")
print("calculated z: " + str(y) + " | FEA z: " + str(beam_system.z_displacements[1]))
print("calculated theta: " + str(dydx) + " | FEA reaction theta: " + str(beam_system.y_angles[1]))
print("calculated moment: " + str(m) + " | FEA moment: " + str(beam_system.y_moments[0]))
print("calculated reaction: " + str(F) + " | FEA reaction z: " + str(beam_system.z_forces[0]))

z_1:  1.224770053114093
z_2:  306.1925132785233
z_3:  102522.52185519996
[[ 1.01363487e+02  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.22477005e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  3.06192513e+02]
 [ 0.00000000e+00  0.00000000e+00  1.22477005e+00  0.00000000e+00
  -3.06192513e+02  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.94898518e+04
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.06192513e+02  0.00000000e+00
   1.02522522e+05  0.00000000e+00]
 [ 0.00000000e+00  3.06192513e+02  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.02522522e+05]]
[[ True  True  True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True]
 [ True  True  True 

In [ ]:
beam_system = BeamSystem("Simple Support Center Load")
arm_beam = BeamType("annulus", [25, 20], "Aluminum7075-T6", "arm_beam")
beam_system.add_node(0,0,0,"origin")
beam_system.add_node(500,0,0,"point_1")
beam_system.add_node(1000,0,0,"point_2")
beam_system.add_beam(arm_beam,"origin","point_1",np.array([0,1,0]),"beam")
beam_system.add_beam(arm_beam,"point_1","point_2",np.array([0,1,0]),"beam")
beam_system.add_boundary_condition(0,"x","origin")
beam_system.add_boundary_condition(0,"y","origin")
beam_system.add_boundary_condition(0,"z","origin")
beam_system.add_boundary_condition(0,"theta x","origin")
beam_system.add_boundary_condition(0,"theta y","origin")
beam_system.add_boundary_condition(0,"x","point_1")
beam_system.add_boundary_condition(0,"z","point_1")
beam_system.add_boundary_condition(0,"x","point_2")
beam_system.add_boundary_condition(0,"y","point_2")
beam_system.add_boundary_condition(0,"z","point_2")
beam_system.add_boundary_condition(0,"theta x","point_2")
beam_system.add_boundary_condition(0,"theta y","point_2")
beam_system.add_force(0,-4,0,"point_1")
beam_system.solve_FEA()

L = 1000
I = (math.pi/64) * (50**4 - 40**4)
E = 71.7
F = 4

y = -(F * (L**3)) / (48 * E * I)
r = F/2
dydx = -(F * L ** 2) / (16 * E * I)

print("Simple Support Center Load")
print("calculated y: " + str(y) + " | FEA y: " + str(beam_system.y_displacements[1]))
print("calculated moment: " + str(0) + " | FEA moment: " + str(beam_system.z_moments[1]))
print("calculated theta center: " + str(0) + " | FEA theta center: " + str(beam_system.z_angles[1]))
print("calculated theta origin: " + str(dydx) + " | FEA theta origin: " + str(beam_system.z_angles[0]))
print("calculated theta edge: " + str(-dydx) + " | FEA theta edge: " + str(beam_system.z_angles[2]))
print("calculated reaction y: " + str(r) + " | FEA reaction y: " + str(beam_system.y_forces[0]))

In [8]:
beam_system = BeamSystem("Cantilever-moment load")
arm_beam = BeamType("annulus", [25, 20], "Aluminum7075-T6", "arm_beam")
beam_system.add_node(0,0,0,"origin")
beam_system.add_node(500,0,0,"point_1")
beam_system.add_beam(arm_beam,"origin","point_1",np.array([0,1,0]),"beam")
beam_system.add_boundary_condition(0,"x","origin")
beam_system.add_boundary_condition(0,"y","origin")
beam_system.add_boundary_condition(0,"z","origin")
beam_system.add_boundary_condition(0,"theta x","origin")
beam_system.add_boundary_condition(0,"theta y","origin")
beam_system.add_boundary_condition(0,"theta z","origin")
beam_system.add_boundary_condition(0,"theta x","point_1")
beam_system.add_boundary_condition(0,"theta z","point_1")
beam_system.add_moment(0,4,0,"point_1")
beam_system.solve_FEA()

L = 500
I = (math.pi/64) * (50**4 - 40**4)
E = 71.7
M = 4

y = (M * L ** 2) / (2 * E * I)
dydx = M * L / (E * I)

# print(beam_system.kuu)
print("Cantilever—moment load")
print("calculated z: " + str(y) + " | FEA z: " + str(beam_system.z_displacements[1]))
print("calculated theta: " + str(dydx) + " | FEA theta: " + str(beam_system.y_angles[1]))
print("calculated reaction force z: " + str(0) + " | FEA reaction z: " + str(beam_system.z_forces[0]))
print("calculated reaction moment y: " + str(-M) + " | FEA reaction moment y: " + str(beam_system.y_moments[0]))

z_1:  1.224770053114093
z_2:  306.1925132785233
z_3:  102522.52185519996
[[   101      0      0      0      0      0   -101      0      0      0
       0      0]
 [     0      1      0      0      0    306      0     -1      0      0
       0    306]
 [     0      0      1      0   -306      0      0      0     -1      0
    -306      0]
 [     0      0      0  19489      0      0      0      0      0 -19489
       0      0]
 [     0      0   -306      0 102522      0      0      0    306      0
   50573      0]
 [     0    306      0      0      0 102522      0   -306      0      0
       0  50573]]
[[  -101      0      0      0      0      0    101      0      0      0
       0      0]
 [     0     -1      0      0      0   -306      0      1      0      0
       0   -306]
 [     0      0     -1      0    306      0      0      0      1      0
     306      0]
 [     0      0      0 -19489      0      0      0      0      0  19489
       0      0]
 [     0      0   -306      0  50573

In [9]:
beam_system = BeamSystem("Cantilever-end load rectangle")
arm_beam = BeamType("rectangle", [25, 10], "Aluminum7075-T6", "arm_beam")
beam_system.add_node(0,0,0,"origin")
beam_system.add_node(500,0,0,"point_1")
beam_system.add_beam(arm_beam,"origin","point_1",np.array([0,0,1]),"beam")
beam_system.add_boundary_condition(0,"x","origin")
beam_system.add_boundary_condition(0,"y","origin")
beam_system.add_boundary_condition(0,"z","origin")
beam_system.add_boundary_condition(0,"theta x","origin")
beam_system.add_boundary_condition(0,"theta y","origin")
beam_system.add_boundary_condition(0,"theta z","origin")
beam_system.add_boundary_condition(0,"x","point_1")
beam_system.add_boundary_condition(0,"y","point_1")
beam_system.add_boundary_condition(0,"theta x","point_1")
beam_system.add_boundary_condition(0,"theta z","point_1")
beam_system.add_force(0,0,-4,"point_1")
beam_system.solve_FEA()

L = 500
I = (25 * (10 ** 3)) / 12
E = 71.7
F = 4
# kuu 
# Z1  Z2
# Z2  Z3
y = - (F * L ** 3) / (3*E*I)
m = F * L
dydx = (F*L**2)/(2*E*I) - (F*L**2)/(E*I)

# print(beam_system.kuu)
print("Cantilever—end load rectangle")
print("calculated z: " + str(y) + " | FEA z: " + str(beam_system.z_displacements[1]))
print("calculated moment: " + str(m) + " | FEA moment: " + str(beam_system.y_moments[0]))
print("calculated reaction: " + str(F) + " | FEA reaction z: " + str(beam_system.z_forces[0]))
print("calculated theta: " + str(dydx) + " | FEA reaction theta: " + str(beam_system.y_angles[1]))

z_1:  0.08913006307909149
z_2:  22.28251576977287
z_3:  7437.816442443219
[[    35      0      0      0      0      0    -35      0      0      0
       0      0]
 [     0      0      0      0      0      3      0      0      0      0
       0      3]
 [     0      0      0      0    -22      0      0      0      0      0
     -22      0]
 [     0      0      0  12754      0      0      0      0      0 -12754
       0      0]
 [     0      0    -22      0   7437      0      0      0     22      0
    3703      0]
 [     0      3      0      0      0   1194      0     -3      0      0
       0    596]]
[[   -35      0      0      0      0      0     35      0      0      0
       0      0]
 [     0      0      0      0      0     -3      0      0      0      0
       0     -3]
 [     0      0      0      0     22      0      0      0      0      0
      22      0]
 [     0      0      0 -12754      0      0      0      0      0  12754
       0      0]
 [     0      0    -22      0   370

In [10]:
k11 = np.array([[1,2],[3,4]])
k12 = np.array([[5,6],[7,8]])
k21 = np.array([[9,10],[11,12]])
k22 = np.array([[13,14],[15,16]])
k1 = np.concatenate((k11, k12), axis=1)
k2 = np.concatenate((k21, k22), axis=1)
k = np.concatenate((k1, k2), axis=0)
print(k)

[[ 1  2  5  6]
 [ 3  4  7  8]
 [ 9 10 13 14]
 [11 12 15 16]]
