In [3]:
import numpy as np
import math 
'''
F0 
Coordinates of vertex 41 :10.92265,114.E-06,-1.E-06
Coordinates of vertex 39 :5.461325,9.459406,-1.E-06
Coordinates of vertex 37 :-5.461325,9.459406,-1.E-06
Coordinates of vertex 35 :-10.92265,114.E-06,-1.E-06
Coordinates of vertex 42 :-5.461325,-9.459179,-1.E-06
Coordinates of vertex 43 :5.461325,-9.459179,-1.E-06

Coordinates of vertex 48 :21.6801,-2.882336,-5.400001
Coordinates of vertex 46 :8.343775,20.216856,-5.400001
Coordinates of vertex 55 :-8.343775,20.216856,-5.400001
Coordinates of vertex 54 :-21.6801,-2.882336,-5.400001
Coordinates of vertex 52 :-13.336325,-17.334179,-5.400001
Coordinates of vertex 50 :13.336325,-17.334179,-5.400001
'''
F0 = np.array([10.92265, 114 * 10**-6, -1 * 10 **-6]) - np.array([21.6801,-2.882336,-5.400001])  
F60 =  np.array([5.461325, 9.459406, -1 * 10 **-6]) - np.array([8.343775,20.216856,-5.400001])
F120 = np.array([-5.461325, 9.459406, -1 * 10**-6]) - np.array([-8.343775,20.216856,-5.400001])
F180 = np.array([-10.92265, 114 * 10**-6, -1 * 10**-6]) - np.array([-21.6801,-2.882336,-5.400001])
F240 = np.array([-5.461325, -9.459179, -1 * 10**-6]) - np.array([-13.336325,-17.334179,-5.400001])
F300 = np.array([5.461325, -9.459179, -1 * 10**-6]) - np.array([13.336325,-17.334179,-5.400001])

R0 = np.array([10.92265, 114 * 10**-6, -1 * 10 **-6])
R60 =  np.array([5.461325, 9.459406, -1 * 10 **-6])
R120 = np.array([-5.461325, 9.459406, -1 * 10**-6])
R180 = np.array([-10.92265, 114 * 10**-6, -1 * 10**-6])
R240 = np.array([-5.461325, -9.459179, -1 * 10**-6])
R300 = np.array([5.461325, -9.459179, -1 * 10**-6])

F0_Dir = F0 / np.linalg.norm(F0)
F60_Dir = F60 / np.linalg.norm(F60)
F120_Dir = F120 / np.linalg.norm(F120)
F180_Dir = F180 / np.linalg.norm(F180)
F240_Dir = F240 / np.linalg.norm(F240)
F300_Dir = F300 / np.linalg.norm(F300)

print("Stage 1 Summary")
print("F0 Dir: ", F0_Dir)
print("F60 Dir: ", F60_Dir)
print("F120 Dir: ", F120_Dir)
print("F180 Dir: ", F180_Dir)
print("F240 Dir: ", F240_Dir)
print("F300 Dir: ", F300_Dir)

# The force in the Z of each member has to be 1/6th of the total because the forces and members are symmetric on three seperate axises. 


M0_C = np.cross(R0,F0_Dir)
M60_C = np.cross(R60,F60_Dir)
M120_C = np.cross(R120,F120_Dir)
M180_C = np.cross(R180,F180_Dir)
M240_C = np.cross(R240,F240_Dir)
M300_C = np.cross(R300,F300_Dir)

Matrix = np.array([
    [F0_Dir[0], F60_Dir[0], F120_Dir[0], F180_Dir[0], F240_Dir[0], F300_Dir[0]],
    [F0_Dir[1], F60_Dir[1], F120_Dir[1], F180_Dir[1], F240_Dir[1], F300_Dir[1]],
    [F0_Dir[2], F60_Dir[2], F120_Dir[2], F180_Dir[2], F240_Dir[2], F300_Dir[2]],
    [M0_C[0], M60_C[0], M120_C[0], M180_C[0], M240_C[0], M300_C[0]],
    [M0_C[1], M60_C[1], M120_C[1], M180_C[1], M240_C[1], M300_C[1]],
    [M0_C[2], M60_C[2], M120_C[2], M180_C[2], M240_C[2], M300_C[2]],
])
print("matrix: ", np.round(Matrix,3))

Force_Moments = np.array([0,0,-120,0,0,0])
F_Vectors = np.linalg.solve(Matrix,Force_Moments)

F0_vector = F_Vectors[0]
F60_vector = F_Vectors[1]
F120_vector = F_Vectors[2]
F180_vector = F_Vectors[3]
F240_vector = F_Vectors[4]
F300_vector = F_Vectors[5]


'''
F_Z_Total = 120/6
Mult_Factor = F_Z_Total / F0_Dir[2]

F0_vector = F0_Dir * Mult_Factor
F60_vector = F60_Dir * Mult_Factor
F120_vector = F120_Dir * Mult_Factor
F180_vector = F180_Dir * Mult_Factor
F240_vector = F240_Dir * Mult_Factor
F300_vector = F300_Dir * Mult_Factor

print("F0 vector: ", F0_Dir * Mult_Factor)
print("F60 vector: ", F60_Dir * Mult_Factor)
print("F120 vector: ", F120_Dir * Mult_Factor)
print("F180 vector: ", F180_Dir * Mult_Factor)
print("F240 vector: ", F240_Dir * Mult_Factor)
print("F300 vector: ", F300_Dir * Mult_Factor)

print("Vector Sum Check:", F0_vector + F60_vector + F120_vector + F180_vector + F240_vector + F300_vector)
'''


F0_mag = np.linalg.norm(F0_vector)
F60_mag = np.linalg.norm(F60_vector)
F120_mag = np.linalg.norm(F120_vector)
F180_mag = np.linalg.norm(F180_vector)
F240_mag = np.linalg.norm(F240_vector)
F300_mag = np.linalg.norm(F300_vector)

print("F0 mag: ", F0_mag, " lbf")
print("F60 mag: ", F60_mag, " lbf")
print("F120 mag: ", F120_mag, " lbf")
print("F180 mag: ", F180_mag, " lbf")
print("F240 mag: ",F240_mag, " lbf")
print("F300 mag: ", F300_mag, " lbf")

Cell_Area = (math.pi/4) * (0.25) ** 2 - (math.pi/4) * (0.25 - 2/16) ** 2
print("Cell_Area", Cell_Area)
Stress0 = F0_mag / Cell_Area
Stress60 = F60_mag / Cell_Area
Stress120 = F120_mag / Cell_Area
Stress180 = F180_mag / Cell_Area
Stress240 = F240_mag / Cell_Area
Stress300 = F300_mag / Cell_Area

Strain0 = Stress0 / 10200000
Strain60 = Stress60 / 10200000
Strain120 = Stress120 / 10200000
Strain180 = Stress180 / 10200000
Strain240 = Stress240 / 10200000
Strain300 = Stress300 / 10200000

print("Stress0: ", Stress0, "lbf/in^2 or psi")
print("Stress60: ", Stress60, "lbf/in^2 or psi")
print("Stress120: ", Stress120, "lbf/in^2 or psi")
print("Stress180: ", Stress180, "lbf/in^2 or psi")
print("Stress240: ", Stress240, "lbf/in^2 or psi")
print("Stress300: ", Stress300, "lbf/in^2 or psi")

print("Strain0: ", Strain0 * 10 ** 6, "microstrain")
print("Strain60: ", Strain60 * 10 ** 6, "microstrain")
print("Strain120: ", Strain120 * 10 ** 6, "microstrain")
print("Strain180: ", Strain180 * 10 ** 6, "microstrain")
print("Strain240: ", Strain240 * 10 ** 6, "microstrain")
print("Strain300: ", Strain300 * 10 ** 6, "microstrain")

# Turn on all energy densities ELEDEN (where the work is) 

Stage 1 Summary
F0 Dir:  [-0.86914524  0.23288676  0.43629153]
F60 Dir:  [-0.23288676 -0.86914524  0.43629153]
F120 Dir:  [ 0.23288676 -0.86914524  0.43629153]
F180 Dir:  [0.86914524 0.23288676 0.43629153]
F240 Dir:  [0.63625848 0.63625848 0.43629153]
F300 Dir:  [-0.63625848  0.63625848  0.43629153]
matrix:  [[-0.869 -0.233  0.233  0.869  0.636 -0.636]
 [ 0.233 -0.869 -0.869  0.233  0.636  0.636]
 [ 0.436  0.436  0.436  0.436  0.436  0.436]
 [ 0.     4.127  4.127  0.    -4.127 -4.127]
 [-4.765 -2.383  2.383  4.765  2.383 -2.383]
 [ 2.544 -2.544  2.544 -2.544  2.544 -2.544]]
F0 mag:  45.837347537702506  lbf
F60 mag:  45.841862328884545  lbf
F120 mag:  45.841862328884545  lbf
F180 mag:  45.837347537702506  lbf
F240 mag:  45.84351508081294  lbf
F300 mag:  45.843515080812956  lbf
Cell_Area 0.03681553890925539
Stress0:  1245.0543682297978 lbf/in^2 or psi
Stress60:  1245.1770009907407 lbf/in^2 or psi
Stress120:  1245.1770009907407 lbf/in^2 or psi
Stress180:  1245.0543682297978 lbf/in^2 or ps

In [7]:
F0 = F0_Dir * F0_mag
F60 = F60_Dir * F60_mag
F120 = F120_Dir * F120_mag
F180 = F180_Dir * F180_mag
F240 = F240_Dir * F240_mag
F300 = F300_Dir * F300_mag
print(F0[2] + F60[2] + F120[2] + F180[2] + F240[2] + F300[2])

120.00000000000001
